baseURL = 'https://vickpalomo.github.io'
languageCode = 'en-us'
title = 'Bravo Site'
theme = "ananke"
relativeURLs = true
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true